### PR TITLE
Add a depth parameter for the -R and --tree options

### PR DESCRIPTION
**Pull request by jorpic**
refs #3 

This adds new option `--depth` to limit recursion depth:

```
$ lsd --tree --depth 0 src
├──   meta
├──   app.rs
├──   batch.rs
├──   color.rs
├──   core.rs
├──   display.rs
├──   flags.rs
├──   icon.rs
└──   main.rs
```

I also added check that `--depth` is not used without `--recursive` or `--tree` (sadly clap does not have something like `requires_any()` modifier).

### CODE REVIEW

**Comment by Peltoche** [comment]
@jorpic ,

Thanks for the PR and the tests! I just made two little comments. Once fixed I merge.

**Comment by jorpic** [comment]
Sorry, don't see any comments.

**Comment by Peltoche** [comment]
Oups, I forgotten to submit the comment. My bad... I just start with the github reviews.

**Comment by jorpic** [comment]
Fixed. Thanks for feedback.

**Pull request merged**
