### PR TITLE
622 block headers

### LINKED ISSUE #622: Block Headers
Is there a way to have block headers?
image

### PR DESCRIPTION
**Pull request by MichaelAug**
closes #622 
---
#### TODO

- [x] Use `cargo fmt`
- [x] Add necessary tests
- [x] Add changelog entry
- [x] Update default config/theme in README (if applicable)
- [x] Update man page at lsd/doc/lsd.md (if applicable)

### CODE REVIEW

**Comment by MichaelAug** [comment]
This is how the header looks like
image

**Comment by meain** [comment]
On second thought should we just use underlines instead of using `-`? It looks like we have a lot of wasted space.

**Comment by MichaelAug** [comment]
> On second thought should we just use underlines instead of using `-`? It looks like we have a lot of wasted space.

Yes, it does look like there's a lot of wasted space. Will update

**Comment by MichaelAug** [comment]
Underlined text looks much better imo :)
image

**Comment by zwpaper** [comment]
Thanks for contributing!

**Pull request merged**
