### PR TITLE
adding a manpage

### PR DESCRIPTION
**Pull request by SirCipherz**
i wrote a manpage for the program, we still need to install it but i haven't figured out how the program install itself

### CODE REVIEW

**Comment by meain** [comment]
Once we have a man page we can bundle that along with the releases. I believe the package maintainers should be able to use that to install the man pages.

The PR seems to be empty though. I think you might have forgotten to commit the file after edits.

**Comment by edneville** [comment]
@SirCipherz, there's a ticket open to package up lsd. I am in the process of doing that now, and just need the manpage at the moment. Can you let me know if the manpage is around, or does it need to be created from new?

**Comment by meain** [comment]
@edneville There is no manpage available for lsd as of now.

**Comment by edneville** [comment]
Ok, I've raised #474 if you wish to consider that. If the man page turns up, maybe they can be combined or mine deprecated later if it is merged? Either way, it will help with packaging to have a man page.

**Comment by meain** [comment]
Closing in favor of https://github.com/Peltoche/lsd/pull/474

**Pull request closed without merging**
