### PR TITLE
Git integration (issue #7)

### PR DESCRIPTION
**Pull request by hpwxf**
Add git integration (cf issue #7)

Use git2-rs to get git info. Unfortunately, it is not available on all targets. To enable it, use `cargo build --features=git`.
In travis config, this feature is enabled using a new FEATURES environment variable (where it is not set, git2-rs does not compile; cf https://travis-ci.com/github/hpwxf/lsd/builds/219208311). 
`git_stub.rs` file contains a minimal set of empty/disabled features to minimize condition compilation in other files.

* New git block is located by default on the left of name block and its location can be set using `--blocks` option
* Use `lsd --git --long` to enable git status info (only available on long display)
* Additional feature: sort by git status using `lsd --sort=git --long`
* Default display use icons. Text display is also available.

Snapshot 3
Snapshot

NB: crate `log` has also been defined in Cargo.toml to provide debug feature. `release_max_level_error` feature disables log macros in release mode.
---
- [x] Use `cargo fmt`
- [X] Add necessary tests
- [X] Add changelog entry

### CODE REVIEW

**Comment by hpwxf** [comment]
Since git2 has inconsistent behaviors on
* arm-unknown-linux-gnueabihf
* i686-pc-windows-msvc
* x86_64-pc-windows-gnu
* x86_64-pc-windows-msvc
and a compilation error on
* i686-pc-windows-gnu
I will investigate what happens in git2.

**Comment by hpwxf** [comment]
* Since git2-rs requires rust 1.45, I had to upgrade RUST_MIN_SRV to 1.45
* Using a complex conditional compilation, git feature is always enabled except on
  *  arm-unknown-linux-gnueabihf (tests fail in git2-rs)
  * i686-pc-windows-gnu (compilation fails in git2-rs)
* new tests have been done to improve overall coverage (not only in new code for git feature)

**Comment by hpwxf** [comment]
NB: to support conditional compilation, I used a stub file (`git_stub.rs`) to provide minimal objects to avoid function signature to change or to be also conditional. This technique could reduce the patch coverage since only one version is covered by tests.

**Comment by meain** [comment]
Hey, sorry about the delay. I have been pretty busy the past few weeks. Will try to get this reviewed by this week.

**Comment by ewen-lbh** [comment]
If I may give feedback, I've been using this branch on my machine for more than a week and found no issues whatsoever.

**Comment by BrandonStaab** [comment]
There is inconsistent behavior when listing outside of a repo vs inside a repo as compared with the yellow squares.  Similarly using `--tree` outside of a repo doesn't display status.

<table><tr>
<td></td>
<td></td>
</tr></table>

**Comment by hpwxf** [comment]
> There is inconsistent behavior when listing outside of a repo vs inside a repo as compared with the yellow squares. Similarly using `--tree` outside of a repo doesn't display status.
> 
> 	

Thank you for your comment. I will check ASAP (probably next week) what happens in this case and how to fix it.

**Comment by BrandonStaab** [comment]
> Thank you for your comment. I will check ASAP (probably next week) what happens in this case and how to fix it.

Also I just noticed that the directory `..` shows a question mark, but it isn't a repo so it shouldn't have any styling.  I put a green box around the mark in question.

**Comment by hpwxf** [comment]
> * Since git2-rs requires rust 1.45, I had to upgrade RUST_MIN_SRV to 1.45
> * Using a complex conditional compilation, git feature is always enabled except on
>   
>   * arm-unknown-linux-gnueabihf (tests fail in git2-rs)
>   * i686-pc-windows-gnu (compilation fails in git2-rs)
> * new tests have been done to improve overall coverage (not only in new code for git feature)

May be https://crates.io/crates/git-repository could be a simple replacement to git2-rs.

**Comment by meain** [comment]
Hey @hpwxf , sorry for kinda abandoning this PR. If you are still interested and won't mind fixing up the conflicts and addressing the previous issue we can get this in.

**Comment by meain** [comment]
> May be [crates.io/crates/git-repository](https://crates.io/crates/git-repository) could be a simple replacement to git2-rs.

What do you think are the primary advantages of switching to this?

**Comment by meain** [comment]
I'm closing this, but if folks want to continue on this, we can open this back up and continue work on this. Sorry that the work you did could not get merged.

**Pull request closed without merging**
