### PR TITLE
Add an icon for .iso files

### PR DESCRIPTION
**Pull request by NyleCohen**
This PR adds an icon for .iso files with the "﫭" ('faed') disk icon.

### CODE REVIEW

**Comment by zwpaper** [comment]
Hi @NyleCohen, thanks for contributing! We arranged the icons by their names, how about moving the `iso` to stay with `i*`

**Comment by NyleCohen** [comment]
Sorry, moved it into alphebetical order

**Comment by zwpaper** [comment]
Seems there is something wrong when tested with my local Hack Nerd Font, I will dig into it and then check this PR.

Seems there is an unexpected space:

image

**Comment by zwpaper** [comment]
@meain I check in my Emacs, the `iso` icon works as expected, but not the terminal and Iterm, could you help to test this icon?

**Comment by meain** [comment]
@zwpaper Looks like it is the same thing for me. Works in Emacs, but not in my terminal emulator. This looks like a terminal rendering bug though. Maybe we can switch to `f7c9`?

**Comment by zwpaper** [comment]
then this is really weird, switching to `f7c9` is a solution but seems the `faed`﫭  suits the case better. 🤨

**Pull request closed without merging**
