### PR TITLE
Clippy lints

### PR DESCRIPTION
**Pull request by auronandace**
Tackling easy Clippy Lints
---
#### TODO

- [ ] Use `cargo fmt`
- [ ] Add necessary tests
- [ ] Add changelog entry

### CODE REVIEW

**Comment by zwpaper** [comment]
hi @auronandace, thanks for contributing, there is one little thing, could we rebase your commits into one, as they were all doing the lint.

**Comment by auronandace** [comment]
@zwpaper I'm really new to GitHub development. How do I do that please?

**Comment by zwpaper** [comment]
it is not related to github, it is a basic git operation, it would be helpful if you would like to catch the software development flow

**Comment by auronandace** [comment]
Sorry, I am totally lost on what I need to do on my end. Can you give me some pointers please?

**Comment by auronandace** [comment]
Oh, wow. Looks like I needed to do a force push. Was that correct?

**Comment by zwpaper** [comment]
yes, you did it! you can always force push on your private branch to clean up or fix some mistake, and never force push to the branches cowork with others

**Comment by auronandace** [comment]
Sorry, I overlooked some brackets in display.rs. Fixed now.

**Comment by zwpaper** [comment]
thanks for contributing!

**Pull request merged**
