### PR TITLE
refactor(name): reduce unnecessary String allocation

### PR DESCRIPTION
**Pull request by TeamTamoad**
This PR improve performance of `escape` and `hyperlink` functions of `Name` struct by reducing number of `String` allocation.

---
#### TODO

- [x] Use `cargo fmt`
- [ ] Add necessary tests
- [ ] Add changelog entry
- [ ] Update default config/theme in README (if applicable)
- [ ] Update man page at lsd/doc/lsd.md (if applicable)

### CODE REVIEW

**Comment by meain** [comment]
Is it really making much of a difference? I was getting mostly mixed results with original version being better(within error margin).

**Comment by TeamTamoad** [comment]
Hmm. Maybe this changes doesn't significantly improve performance of the program. However, I'll try writing a benchmark to test performance `render`, `escape` and `hyperlink` functions of `Name` struct.
What do you think about `Cow<str>`? Do you have any concern about its complexity?

**Comment by meain** [comment]
> Do you have any concern about its complexity?

As long as it provides some perf improvement, I don't mind the added complexity.

**Comment by meain** [comment]
I'm closing this PR for now. We can revisit it later if you think this could improve things here.

**Pull request closed without merging**
