### PR TITLE
Icons: added clang-format

### PR DESCRIPTION
**Pull request by TruncatedDinosour**
I just mainly added it for myself, you
can choose if merge or not, it's just nice
to see the config file icon as .clang-format
is a configuration file... well for clang-format

Not an important feature, just nice I guess lol

Just close this PR if you decide not to merge :)

Signed-off-by: Ari Archer <truncateddinosour@gmail.com>

---
#### TODO

- [ ] Use `cargo fmt`
- [x] Add necessary tests (none)
- [ ] Add changelog entry

### CODE REVIEW

**Comment by zwpaper** [comment]
hi @TruncatedDinosour, thanks for the PR, contributions are always welcomed! feel free to open an Issue or PR anytime.

**Comment by zwpaper** [comment]
it seems that it is not necessary to update the `cargo.lock`, could you drop its edit and update the PR?

we could update the `lock` file in a separate PR if needed

**Comment by TruncatedDinosour** [comment]
> it seems that it is not necessary to update the `cargo.lock`, could you drop its edit and update the PR?
> 
> we could update the `lock` file in a separate PR if needed

oh okay, let me figure out how to remove the file lol

**Comment by TruncatedDinosour** [comment]
here we go

**Comment by meain** [comment]
Hey, thanks for the PR, but that icon actually looks like a folder icon which might bend up being confusing to people.

**Comment by TruncatedDinosour** [comment]
> Hey, thanks for the PR, but that icon actually looks like a folder icon which might bend up being confusing to people.
> 
> I don't know what a good icond would be, maybe we could use `\u{e615} `? This is what is used for `.editorconfig` currently.

sure thing

**Comment by TruncatedDinosour** [comment]
now other files are changed, wait

**Pull request merged**
