### PR TITLE
Hyperlink

### PR DESCRIPTION
**Pull request by KSXGitHub**
Fix https://github.com/Peltoche/lsd/issues/192

## Preview

preview: `lsd --hyperlink=always -1`

## Remaining Issues

It works well with `-1` flag, but it prints a [broken list](https://user-images.githubusercontent.com/11488886/79633337-f725a500-818e-11ea-923b-ef747b5b2fcf.png) without it. I can guess this is due to width of filenames not being calculated correctly: It did not strip away ANSI symbols first. I will not try fixing it as reading the source code alone had sucked the energy out of me.

### CODE REVIEW

**Comment by KSXGitHub** [comment]
I don't know why the tests fail on Windows, or if it was because of my doing, I don't have Windows, I can't fix it by myself.

**Comment by meain** [comment]
Don't worry about the windows builds for now, it is a known issue and is being tracked in https://github.com/Peltoche/lsd/issues/350

**Comment by meain** [comment]
The actual length needs to be computed https://github.com/Peltoche/lsd/blob/d77fe699b5d610fbb9a9d4838c230ae3a6df04f4/src/display.rs#L266 here and we need to make sure the url length does not count in.

**Comment by KSXGitHub** [comment]
I think it is easier to get invisible width than to get visible one.

**Comment by meain** [comment]
@KSXGitHub yeah, the function is pretty much computing the invisible width and subtracting it from the total one.

**Comment by KSXGitHub** [comment]
@meain Actually, why compute visible width at all? Why don't we use length of filenames directly?

**Comment by meain** [comment]
This function is actually used to compute the length of all the items inside lsd, not just for filenames.

Actually, it is an option that we can pass along the "true length" of each item along with the coloured value.

**Comment by KSXGitHub** [comment]
@meain Perhaps instead of trying to fix `get_visible_width`, I think we should invest our time in implementing "true length" for less error-prone and faster code. I may work on this when I have the time, but if someone else wants to do it, then it would be great.

**Pull request closed without merging**
