### PR TITLE
Fix Bug: Handle -L with broken symlink #457

### PR DESCRIPTION
**Pull request by r3dArch**
This is a draft PR for https://github.com/Peltoche/lsd/issues/457.

---
#### TODO

- [ ] Use `cargo fmt`
- [ ] Add necessary tests
- [ ] Add changelog entry
- [ ] Update default config/theme in README (if applicable)
- [ ] Update man page at lsd/doc/lsd.md (if applicable)

### CODE REVIEW

**Comment by meain** [comment]
Sorry about the delayed response. I somehow missed the PR. This looks great. Could you add tests for this behavior and a changelog entry and we should be good to go.

**Comment by r3dArch** [comment]
Thank you for the response. I'll make those changes soon and let you know when they are ready.

**Comment by r3dArch** [comment]
@meain I have added tests and updated the changelog, although I do not have a Windows device to run the tests. [According to the Rust docs](https://doc.rust-lang.org/std/os/windows/fs/fn.symlink_file.html), symlink creation on the Windows OS is a privileged action, so these tests will probably fail on Windows. Should I make these tests Unix only? What are your thoughts? Thanks.

**Comment by meain** [comment]
@r3dArch The CI should be able to run Windows test. With that said, if the test are gonna fail on Windows, we can run it on just linux and macOS.

**Comment by meain** [comment]
Merging another PR causing some conflicts, could you also take care of that :D.

**Comment by r3dArch** [comment]
@meain I fixed a clippy warning pointed out by the CI/CD and the conflicts caused by the other PR. Is there anything else needed for this to be merged? Clippy points out some other style problems, but they are not from the changes I made.

**Comment by meain** [comment]
Thanks again for the PR :D.

**Comment by r3dArch** [comment]
Thank you. This was actually my first contribution to someone else's project, so it is really nice it got merged :D.

**Comment by meain** [comment]
To more to come! 🍷 🍾 😉

**Pull request merged**
