### PR TITLE
Add separator to sample config file.

### PR DESCRIPTION
**Pull request by LHY-iS-Learning**
Add separator to sample config file

### CODE REVIEW

**Comment by zwpaper** [comment]
hi @LHY-iS-Learning , thanks for updating the doc, I have one more concern, we specify the default values in the config file example, but looks like there is only one space in the separator value?
maybe we should make it the default 2 spaces

**Comment by meain** [comment]
@zwpaper the default is single space ([ref](https://github.com/Peltoche/lsd/blob/7d04dcbeafaa53020d2800f30fec5f5d9922c386/src/flags/icons.rs#L172)). I think we will stick to that for now.

**Comment by LHY-iS-Learning** [comment]
Em,,, my bad.
Update to one space comment.

**Comment by meain** [comment]
Thanks @LHY-iS-Learning !

**Pull request merged**
