### PR TITLE
added color documentation/FAQ-Section

### PR DESCRIPTION
**Pull request by Termuellinator**
as per https://github.com/Peltoche/lsd/issues/120 i've added the colors i've found in /src/color.rs to the readme/FAQ.
Please check if i understood everything right in the code ;)

### CODE REVIEW

**Comment by meain** [comment]
@Termuellinator Thanks a lot for the PR, but I think it would be better to use a placeholder image service to show the color. This will avoid having to keep images in the repo.

Something like
```
![#b00202](https://placehold.it/15/b00202/000000?text=+) User
```
will give you 

#ffffd8 User

**Comment by Termuellinator** [comment]
@meain that is indeed a more elegant solution, thank you - you never stop learning ^^
i've replaced the images with placeholders now.

**Comment by Peltoche** [comment]
Hello @Termuellinator ,

Thanks a lot for this PR, it really great!

**Comment by Termuellinator** [comment]
I've learnt how to squash commits together now, but i think using --force wasn't the best idea to push...and now i can't seem to be able to squash away the merging commit (that was created by clicking on "merge branches" here in github), no matter which tutorial i try :/

**Comment by meain** [comment]
@Termuellinator Force pushing is the way to go.

 Just reset the merging commit using 

`git reset --hard HEAD~1`

Now rebase it with master using. 

`git pull upstream master --rebase`

I'm guessing upstream is the name that you have set for this remote.

Now just force push the rebased commit

**Comment by Termuellinator** [comment]
uhm - now i've got some of your commits in here?! O_o is that a problem or expected behaviour?
but i guess the history is more tidy now ^^

**Comment by meain** [comment]
@Termuellinator Oh, that went wrong, my bad.

Could you just do a reset using the below command and force push the result.

`git reset --hard HEAD df1d7ff355d79cd1e70df30259b10a485e710d95`

**Comment by Termuellinator** [comment]
that yields
"fatal: Ein 'hard'-Reset mit Pfaden ist nicht möglich."
-> "a 'hard'-reset using paths is not possible"

**Comment by meain** [comment]
Could you show me the result of

`git log --oneline -10`

**Comment by Termuellinator** [comment]
415e34e (HEAD -> master, origin/master, origin/HEAD) switch to one line when not outputting to tty
437fbfa Fix the module import paths
5d5511a Drop the support of V1.30.1 and move to the rust 2018 edition
df1d7ff added color documentation/FAQ-Section
e1138bb Refactored classic mode
1b7eec3 Added --classic flag
373a218 Update Cargo.toml
0fa6809 Improve the tree display
73bcd96 Fix some display errors inside the CHANGELOG
5b28831 (cargo-release) start next development iteration 0.12.1-pre

the strange thing is/was that i couldn't see the merger-commit in git log, even after fetch/pull/rebase yet git status says i've got the current master.
Up until the merging git was pretty straight forward, but now i'm more confused about it than i ever was ^^

**Comment by meain** [comment]
@Termuellinator My bad I had edited the command, just after I posted the message.

**Comment by Termuellinator** [comment]
oh, OK, now i see the error in the reset-command i tried after your first suggestion.
Now there is only one commit, but at the bottom it says "This branch is out-of-date with the base branch" (thats where the merging-commit came from before).
i won't press "update branch" now ^^
but can this PR be merged with this out-of-date message?

**Comment by meain** [comment]
now do a rebase

**Comment by Termuellinator** [comment]
right, forgot about that one.
But it's saying its up-to-date already:
```
~/.../git/lsd >>> git reset --hard df1d7ff355d79cd1e70df30259b10a485e710d95          ±[●][master]
HEAD ist jetzt bei df1d7ff added color documentation/FAQ-Section
~/.../git/lsd >>> git pull origin master --rebase                                                                ±[●][master]
Von https://github.com/Termuellinator/lsd
 * branch            master     -> FETCH_HEAD
Bereits aktuell.
Aktueller Branch master ist auf dem neuesten Stand.
```
i don't think i should re-add the readme.md, that would yield a new commit, right?

**Comment by meain** [comment]
`git pull upstream master --rebase`

upstream not origin

**Comment by Termuellinator** [comment]
that yields an error:
```
~/.../git/lsd >>> git pull upstream master --rebase                                                              ±[●][master]
fatal: 'upstream' does not appear to be a git repository
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
```
i used origin because of your "I'm guessing upstream is the name that you have set for this remote."

now i've learned about remotes and added this one as upstream, now the rebase works and everything seems to finally be in order as far as i can see! :)

thanks so much for your guidance! 

one more question for my understanding though: is adding the upstream-repo as a remote a standard procedure that should be done with every project?

**Comment by meain** [comment]
Yeah, I guess that's a thing people do.

**Comment by Peltoche** [comment]
Thanks to you guys! Merged

**Pull request merged**
