### PR TITLE
Add GitHub CICD workflow; full automated testing and deployment (all platforms)

### LINKED ISSUE #188: Windows Builds
Can we get some compiled builds for this application on the GitHub Releases page? I personally wouldn't mind compiling it for x86-64 and i686 for version 0.13.0 and 0.14.0 if it means it would land on the Releases page. Currently only Apple Macintosh and GNU/Linux are distributed, I feel it would be a lot more convenient for Windows Users if pre-compiled builds in some form were available to us.

### PR DESCRIPTION
**Pull request by rivy**
> fixes #188 

I built and iterated this GitHub workflow to mimic the observable CI that you already have via Travis CI. Notably, this automation builds and saves executable artifacts for all of the supported platforms, including Windows. As GitHub actions are fairly new (and still a bit rough IMO), it took a couple of weeks to develop and smooth out the process.

But, ultimately, I've included "Style" checks, a "MinSRV" test, "Build" (with testing and saved artifacts) for all platforms, and "Code Coverage" (with optional upload to CodeCov.io if the CODECOV_TOKEN secret is set for the repository).

- [GHA automation output for this PR](https://github.com/rivy/rust.lsd/commit/6734df063f9d75eea4e611d15d994bce4cfae400/checks?check_suite_id=336976057) (saved artifacts are located in the top-right "Artifacts" drop-down)
- [CodeCov info for this PR](https://codecov.io/gh/rivy/rust.lsd/branch/add.gha); textual code coverage output is included in the output of the "Code Coverage" step in the GHA automation output above

Additionally, I've included automation for deployment to GitHub Releases. When tagged with a version tag (~"[vV]?[0-9].*"), a GitHub Release corresponding to that tag will be automatically created. All platform packages (including `dpkg` packages) are attached as assets. No GitHub API secret is required, so contributors gain the same full automation.

- [example (completely automatic/no touch) "0.16.3" release](https://github.com/rivy/rust.lsd/releases/tag/0.16.3)

All changes to files other than *.github/workflows/CICD.yml* are purely refactors for `cargo clippy` and `cargo fmt`.

Please let me know if there are any problems on your side and if you need any changes.

### CODE REVIEW

**Comment by rivy** [comment]
I forgot to mention that I haven't been able to get the "*-pc-windows-gnu" targets to build. There are multiple `gcc` compilers included in the windows VM workers that seem to interfere with compilation/linking for that platform. If anyone can get the working or knows of a working CI for it, I'd love to see the recipe.

**Comment by rivy** [comment]
"*-pc-windows-gnu" target fixed.
"i686-apple-darwin" target removed (unable to build 32-bit targets with Xcode > v9.4).

**Comment by Peltoche** [comment]
Damn @rivy , that's neat!

I always wanted to play with the Github workflow but I didn't have the time. I merge it and we will see the behaviour.

**Comment by rivy** [comment]
Hmm, I see that the GitHub automation is failing because workflows aren't "enabled" for your account.
I'm not sure why that would be... I did find a [community thread](https://github.community/t5/GitHub-Actions/GitHub-Actions-workflows-can-t-be-executed-on-this-repository/m-p/38153) discussing this issue. 

Is your account a "legacy" account?
Or, possibly switching to $0/year billing or a pure FOSS-only organization might help.
Otherwise, you might contact GitHub support to check into the issue.

**Comment by Peltoche** [comment]
It should be ok now :+1:

**Pull request merged**
