### PR TITLE
docs(readme): add repology badge

### PR DESCRIPTION
**Pull request by tranzystorek-io**
Adds repology badge for a quick overview of different available packages of `lsd`

---
#### TODO

- [ ] Use `cargo fmt`
- [ ] Add necessary tests
- [ ] Add changelog entry
- [ ] Update default config/theme in README (if applicable)
- [ ] Update man page at lsd/doc/lsd.md (if applicable)

### CODE REVIEW

**Comment by meain** [comment]
This looks like a good addition,but having this gigantic thing right at the starts feel like a bit too much. What is your opinion on moving it to the very end and maybe linking to a heading from the installation section?

**Comment by tranzystorek-io** [comment]
I added the parameter to the link so that it's split into three columns, shouldn't be too big:

obraz

But of that's still too sizable then yeah, sure linking seems fine

**Comment by meain** [comment]
I did see that 3 column layout, but I feel like it is still too big. Something like 5 would be good, but then it becomes unusable on a mobile. I think we will just link to it.

**Comment by tranzystorek-io** [comment]
> I guess, we can have it as a collapsed section here as well using `<details>` thingy.

Switched to the html version of the badge wrapped in details, IMO looks fine now 😄

**Comment by meain** [comment]
I guess that ain't that bad.

**Pull request merged**
