### PR TITLE
let lscolors apply default colors if LS_COLORS not defined

### LINKED ISSUE #90: Use terminal color scheme
## Expected behavior
`lsd` uses colors from my terminal color scheme, being consistent with all the other command line tools.

## Actual behavior
It appears `lsd` uses hard-coded colors, instead of the terminal color scheme. The hard coded colors don't look as nice. See screenshot below.

image

My terminal colors:
image

### PR DESCRIPTION
**Pull request by meain**
Fixes #90

### CODE REVIEW

**Comment by Kevin-Mok** [comment]
This doesn't seem to work for me. The compiled binary still uses the hardcoded colors.

**Comment by meain** [comment]
@Kevin-Mok  Hmm, that is interesting.

We depend on a tool called `lscolors` to do the coloring.
Is it possible for you to check if [lscolors](https://github.com/sharkdp/lscolors) gives you the right colors.

You could do it by 

```sh
cargo install lscolors  # creates a binary
lscolors *
```

**Comment by Kevin-Mok** [comment]
Ah, so `lscolors` doesn't work for me - it just hangs. Not sure why.

**Comment by meain** [comment]
@Kevin-Mok 

Just running `lscolors` will wait for input, you have to run `lscolors *` or `lscolors` with some filename.

**Comment by Kevin-Mok** [comment]
:man_facepalming: Right. So, `lscolors` does give me the correct colors.

**Pull request merged**
